packages:
- .
extra-deps:
# tree-view
- tree-view # local version
# for type nats comparison
- typelits-witnesses-0.3.0.2 #use local version for GHC 8.6.1
- base-compat-0.10.4
- constraints-0.10.1
- reflection-2.1.4
- hashable-1.2.7.0
- semigroups-0.18.5
- transformers-compat-0.6.2
# knownnat plugins
- ghc-typelits-knownnat-0.6
- ghc-typelits-natnormalise-0.6.2
- ghc-tcplugins-extra-0.3
# singletons
- singletons-2.5
- syb-0.7
- th-desugar-1.9
- th-expand-syns-0.4.4.0
- th-lift-0.7.11
- th-orphans-0.13.6
- th-abstraction-0.2.8.0
- th-lift-instances-0.1.11
- th-reify-many-0.1.8
- safe-0.3.17
- vector-0.12.0.1
- primitive-0.6.4.0

flags:
  transformers-compat:
    five-three: true

#compiler: ghc-8.6.1
resolver: ghc-8.4.3
#compiler-check: match-exact
#resolver: nightly-2018-10-01

#setup-info:
#  ghc:
#    windows64:
#      8.6.1:
#        url: https://downloads.haskell.org/~ghc/8.6.1/ghc-8.6.1-x86_64-unknown-mingw32.tar.xz
#        sha256: 7316d9cb5e486460476754f872c7bac30ee2082e42f46da4342f872d10b88099